### PR TITLE
Add Portuguese version of index.

### PR DESCRIPTION
**Pull request by m4ktub**

### CODE REVIEW

**Comment by checksum0** [comment]
I think it's time we take two seconds and think of where we are going with the translation issue here, I'd like to hear people's opinion on it.

The end goal is to obviously have a centralized system for translation using something like transifex. Bitcoin.org have been doing an awesome job at it over the years and I think they are the end goal.

So, we have to consider not all translators can make alternate index.html page. I know a template has been created for them.

We have two options from here.

1. Integrate index.lang.html page as a temporary translation measure and create a new branch to implement a centralized translations mean

or 

2. Go ahead right away with the centralized measure and forgo the time spent on individual page translations.

Comments?

**Comment by zquestz** [comment]
I would vote to add a build system that generates the pages. The nginx logic looks fine to me. Ideally we have yaml files that are for each translation, then run a script that will generate the appropriate html files This will be far easier for translators to manage, and doesn't require any complex changes.

**Comment by BitcoinCashFund** [comment]
So, just so that I am clear on things, the issue is that translators currently have to go into the HTML code and edit the text inside it? This is made slightly easier by having a template for translators to fill out?

Obviously, we want to make it as easy as possible for translators to add their work to the site. I think it is worth keeping in mind though that this version of the site will not have many changes made to it (other than translations). It was just designed to be a simple homepage for the BCF to have a web presence. So a simple solution might be best for now, and we can consider a longer-term solution for the next website.

I am willing to defer to anyone else on this though.

**Comment by Solon-Archon** [comment]
So, just so that I am clear on things, the issue is that translators currently have to go into the HTML code and edit the text inside it? This is made slightly easier by having a template for translators to fill out?

Obviously, we want to make it as easy as possible for translators to add their work to the site. I think it is worth keeping in mind though that this version of the site will not have many changes made to it (other than translations). It was just designed to be a simple homepage for the BCF to have a web presence. So a simple solution might be best for now, and we can consider a longer-term solution for the next website.

I am willing to defer to anyone else on this though.

**Comment by zquestz** [comment]
@singularity87 Exactly. The idea is to make an html template that gets filled out with the different translations that exist in yaml files. Then the translators don't need to edit the html directly. I am not tied to any particular approach, but I have found in the past this is less error prone than html edits.

**Comment by m4ktub** [comment]
I was also operating with the assumption that this static, single-page site would have reduced number of changes until the final website is set up. That's why I was willing to isolate other translators from the technical knowledge needed to submit/update a translation like this one.

Still, having a simple system like the one proposed by @zquestz  seems a good and quick step. It would reduce the risk of having me be a bottleneck, for example. I've used something quick and dirty for my translation so I'll investigate and make a new PR when I get the chance.

The effort for a _centralized system for translation_ should be done in parallel and be focused on providing a solution for the new version of the site, in my opinion.

Also, note that this PR is based on #5 so the only change that is actually being proposed here it the inclusion of `index.pt.html`.

**Pull request merged**
